### ISSUE TITLE
Send interrupt (hard on windows)

### ISSUE THREAD

**Issue by richfitz** [r-pkgs/processx#33]
In addition to `$kill()` it would be nice to have `$interrupt()`.

On unix/macos this can be implemented as

```r
process_interrupt <- function(self, private) {
    "!DEBUG process_interrupt '`private$get_short_name()`', pid `private$pid`"
    if (!is.null(private$pid)) {
        pids <- c(private$pid, get_pid_tree(private$pid))
        pskill(pids, SIGINT)
    }
    invisible(self)
}
```

but on windows I think that this will kill the process

```
     Only ‘SIGINT’ and ‘SIGKILL’ will be defined on Windows, and
     ‘pskill’ will always use the Windows system call
     ‘TerminateProcess’.
```

(from `?pskill`).  Googleing around suggests that this is hard, if not impossible, to do on windows :cry:

**Comment by gaborcsardi** [comment]
What is your motivation? Are you trying to catch the signal in the external program? Or just want a more graceful shutdown? 

Also, do you really want to send the signal to all child processes?

**Comment by richfitz** [comment]
Essentially graceful shutdown essentially, yeah.

The child process is an R process, so sending the signal through to it's children turns out to be needed (at least starting R from a hashbang Rscript script).

Within the process I've got a `repeat` loop wrapped with `tryCatch(..., interrupt = function(e) {...})`

**Comment by gaborcsardi** [comment]
We do send a `TERM` first:

https://github.com/r-pkgs/processx/blob/6f77a3830839968f624ed689201197f972c8dca2/R/kill.R#L27-L29

Isn't that enough? I have no idea, I am just asking....

**Comment by richfitz** [comment]
Nope, that terminates the R process and skips cleanup (just checked). This is not a huge deal for me, so if you feel it's not in scope don't worry

**Comment by gaborcsardi** [comment]
No, it's fine I think, we can send arbitrary signals, I guess. 

Or we can just extract the PID, that can also be useful.

**Comment by gaborcsardi** [comment]
This is now implemented in the `c` branch. It will be merged soon I think, I just need to write more tests....

**Comment by gaborcsardi** [comment]
I mean, there is no `interrupt`, but you can send a signal on unix.... Only INT, TERM and KILL on windows, and they all kill....
