### ISSUE TITLE
supervisor_kill can leave behind zombies

### ISSUE THREAD

**Issue by wch** [r-pkgs/processx#53]
Running `supervisor_kill()` can leave behind zombie processes, on both Mac and Linux:

```R
library(processx)
process$new('sleep', args='1000', commandline=NULL, cleanup=F, supervise=T)
process$new('sleep', args='1000', commandline=NULL, cleanup=F, supervise=T)
process$new('sleep', args='1000', commandline=NULL, cleanup=F, supervise=T)
process$new('sleep', args='1000', commandline=NULL, cleanup=F, supervise=T)
process$new('sleep', args='1000', commandline=NULL, cleanup=F, supervise=T)
processx:::supervisor_kill()
```

Running `ps` after the R code above:

```
$ ps aux | grep sleep
winston          60850   0.0  0.0        0      0   ??  Z     4:33PM   0:00.00 (sleep)
winston          60848   0.0  0.0        0      0   ??  Z     4:33PM   0:00.00 (sleep)
winston          60862   0.0  0.0  2432804   2000 s004  S+    4:34PM   0:00.00 grep sleep
```

`supervisor_kill()` usually runs only when R exits, and so it won't leave behind zombie processes, but even so, this should not happen.

When `supervisor_kill()` is called, this code that sends SIGTERMs is run: https://github.com/r-pkgs/processx/blob/a60d83a/src/supervisor/supervisor.c#L144-L153

Is it possible that this is happening because the SIGCHLD events are coming very close together and the SIGCHLD handler can't handle them that quickly?

**Comment by gaborcsardi** [comment]
This is exactly the case when multiple children exit around the same time, and a single `SIGCHLD` is delivered. So the rest are not cleaned up. 

It is good to have an issue for it, though!

**Comment by gaborcsardi** [comment]
I think this should be fixed now, let me know if not!

**Comment by wch** [comment]
Excellent!
