### ISSUE TITLE
Allow termination from RStudio

### ISSUE THREAD

**Issue by hadley** [r-pkgs/processx#54]
Is there any way we could make this killable from RStudio?

```R
processx::run("sleep", "20")
```

I don't know whether this a something processx can do (by listening for interrupts and propagating?) or whether it's something that RStudio needs to do, or both.
 
cc @wch @kevinushey

**Comment by gaborcsardi** [comment]
Interesting. It is running an event loop in R, so I thought that would be interruptible.  

It seems that it is interruptible if the event loop actually does something (more), e.g. having `spinner = TRUE` already fixes it.

This is definitely sg that `run()` can handle.

**Comment by gaborcsardi** [comment]
This is not RStudio specific, actually.

**Comment by gaborcsardi** [comment]
Oh, yes, it makes sense, if there is no spinner, or output from the child process, then we are just waiting at a `poll()` and that is not interruptible currently....

**Comment by gaborcsardi** [comment]
OK, fixed on Unix, need to check Windows as well, although I suspect that this is not an issue there.

**Comment by gaborcsardi** [comment]
No problems on Windows.

**Comment by hadley** [comment]
I just tried with latest processx, R 3.4, and RStudio daily, and it doesn't work for me

**Comment by gaborcsardi** [comment]
Ok, looks like there were two issues, actually, and I only fixed the non-rstudio-specific one.

**Comment by kevinushey** [comment]
RStudio had a general issue with the interruption of child processes launched through `system()`, e.g. this is not interruptible:

```
system("sleep 10")
```

So I imagine `processx` is bumping into the same problem.

**Comment by gaborcsardi** [comment]
@kevinushey Yeah, maybe. How do you handle interrupts in general? Do you send a SIGINT to the R process? Or embedded R has some support for this?

**Comment by kevinushey** [comment]
We basically have some code that responds to RStudio interrupt requests like this:

```
            // only accept interrupts while R is processing input
            if (console_input::executing())
               rstudio::r::exec::setInterruptsPending(true);
```

In other words, all we try to do is tell R that interrupts are pending. We might want to ask JJ if he can offer any insight as to what we could do here.

**Comment by gaborcsardi** [comment]
Maybe you could send a SIGINT, I don't know. 

But for this issue, it does not matter, I just need to check for the interrupts in `processx`. It is a bit more effort, but it is ok. Instead of a simple `poll(..., timeout)`, I'll just poll in smaller time chunks.

**Comment by gaborcsardi** [comment]
I fixed `run()`, that's easy. But this is still not interruptable:
```
library(processx)
p <- process$new("sleep", "20", stdout = "|")
p$poll_io(-1)
```

To fix this, I need to poll in (say) 200ms time chunks in C.

**Comment by hadley** [comment]
This is awesome!
